const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEMS: 'ADD_ITEMS',
  DECREASE_ITEMS: 'DECREASE_ITEMS',
  CLEAR_ITEMS: 'CLEAR_ITEMS',
  CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes;